### ISSUE TITLE
Problem in FreiHand data-loader

### ISSUE THREAD

**Issue by ZhimaoPeng** [hongsukchoi/Pose2Mesh_RELEASE#11]
When I tried to train the PostNet on the FreiHand dataset, I got the following errors:
  
File "/home/nankaingy/data/code/pose-shape/Pose2Mesh_RELEASE/main/../data/FreiHAND/dataset.py", line 202, in __getitem__
    mano_mesh_cam, mano_joint_cam = self.get_mano_coord(mano_param, cam_param)
  File "/home/nankaingy/data/code/pose-shape/Pose2Mesh_RELEASE/main/../data/FreiHAND/dataset.py", line 172, in get_mano_coord
    R, t = np.array(cam_param['R'], dtype=np.float32).reshape(3, 3), np.array(cam_param['t'], dtype=np.float32).reshape(3)
KeyError: 'R'

Since the argument ‘cam_param’ loaded from 'freihand_train_data.json'，the keys of ‘cam_param‘ dict in JSON file only contains 'focal' and 'princpt' without 'R' or 't', as shown below: 

freihand_$SPLIT_data.json
|-- db_idx: {
		‘cam_param’: {
				‘focal’: focal lengths in x- and y-axis (intrinsic. pixel unit.),
				‘princpt’: principal point coordinates in x- and y-axis (intrinsic. pixel unit.)
				},
		‘mano_param’: {
				‘pose’: 48-dimensional mano pose vector (theta),
				‘shape’: 10-dimensional mano shape vector (beta)
				},
		‘joint_3d’: 21x3 joint coordinates (MANO joint set. meter unit.) from mesh,
		‘scale’: groundtruth scale provided from FreiHAND
		}
How can I fix this?

**Comment by hongsukchoi** [comment]
@ZhimaoPeng 

There was a mismatch between FreiHAND/dataset.py and the json files.
I replaced the json files, so you could download the proper json files!
