### ISSUE TITLE
How to get the  Joint regressor for coco format

### ISSUE THREAD

**Issue by icech** [hongsukchoi/Pose2Mesh_RELEASE#12]

**Comment by icech** [comment]
I am very curious about how to get the Joint regressor for coco format

**Comment by hongsukchoi** [comment]
Hi @icech , are you talking about 'J_regressor_coco.npy'?

The joints in a face (eyes, nose, ears) are sampled manually from the mesh vertices.
Other joints are mainly brought from the smpl joint regressor.

**Comment by icech** [comment]
Yep. Thanks for your kind reply.
