### ISSUE TITLE
Ground truth mesh image correspondence

### ISSUE THREAD

**Issue by Shubhendu-Jena** [hongsukchoi/Pose2Mesh_RELEASE#18]
Hi,

Thank you for the great work. I had a small question about the data. For 3DPW and COCO, which has images with multiple people in it (even after cropping using the bounding box coordinates provided in your annotations), how did you decide which person to fit the mesh for? Attaching a cropped example for reference from the 3DPW dataset. I'd be grateful if you could let me know as I want to find out the correspondence between the person and the ground truth mesh for every image in COCO/3DPW datasets.

Thanks in advance :)
![full3](https://user-images.githubusercontent.com/12934176/120086085-91b81d80-c0dd-11eb-8da8-e2ce65268d26.png)

**Comment by hongsukchoi** [comment]
Hi Shubhendu, 

The GT meshes of 3DPW are provided in the original annotation along with the 2dd joint coordinates, bounding boxes and so on.
We obtained pseudo-GT meshes of COCO by fitting SMPL parameters to the 2D joint coordinates in their annotation.

**Comment by Shubhendu-Jena** [comment]
Hi. Thank you for the quick response. Thanks for the insight. However, my question is that for a particular image frame, I can see only one vector smpl shape (of size 10) and pose param (of size 72) while there is more than one person in the image frame. This means that the mesh has been fit to one of the persons in the image frame. Is there a way to find which one that is?
![Screenshot from 2021-05-31 15-53-33](https://user-images.githubusercontent.com/12934176/120204433-182d4600-c229-11eb-9351-df91c247825f.png)

**Comment by Shubhendu-Jena** [comment]
Apologies. Issue solved. Closing now.
