### ISSUE TITLE
Question about the multiple datasets loader.

### ISSUE THREAD

**Issue by rainypurplesky** [hongsukchoi/Pose2Mesh_RELEASE#21]
Hi. Thanks for your code sharing.
I have a question about your code, part of multiple datasets loading.
```python


    class MultipleDatasets(Dataset):
       ...
        def __getitem__(self, index):
            if self.make_same_len:
                db_idx = random.randint(0,self.db_num-1) # uniform sampling
                data_idx = index % self.max_db_data_num
                if data_idx >= len(self.dbs[db_idx]) * (self.max_db_data_num // len(self.dbs[db_idx])): # last batch: random sampling
                    data_idx = random.randint(0,len(self.dbs[db_idx])-1)
                else: # before last batch: use modular
                    data_idx = data_idx % len(self.dbs[db_idx])
        ...
            return self.dbs[db_idx][data_idx]
```

```python

if data_idx >= len(self.dbs[db_idx]) * (self.max_db_data_num // len(self.dbs[db_idx])): # last batch: random sampling
    data_idx = random.randint(0,len(self.dbs[db_idx])-1)
else: # before last batch: use modular
    data_idx = data_idx % len(self.dbs[db_idx])

```

I cannot understand these 4 lines. When We get an item from this class. 
For my understanding, data_idx should be [0, self.max_db_data_num * self.db_num -1] if self.make_same_len is true.
But the length of self.dbs[db_idx] can be smaller than data_idx. In this case, you can simply get the modular as valid data_idx.

But why do we need the condition like this?
```python
if data_idx >= len(self.dbs[db_idx]) * (self.max_db_data_num // len(self.dbs[db_idx]))
```
And why data_idx should be drown out by random sampling in this case??

May be a trivial question, but i want to know your purpose! Thank you :)

**Comment by hongsukchoi** [comment]
@rainypurplesky 

Hi, the purpose is to uniformly sample data from `self.dbs[db_idx]`.
> But the length of self.dbs[db_idx] can be smaller than data_idx. In this case, you can simply get the modular as valid data_idx.

If you sample as you suggested, you are likely to sample more data from the front part of `self.dbs[db_idx]`.
For example, let's assume `self.max_db_data_num` is 10000, the current `self.dbs[db_idx]` is 1500, and `self.db_num` is 2.
`data_idx` ranges form 0 to 9999, and 0th\~999th data of `self.dbs[db_idx]` should be sampled once more than 1000th\~1499th data. 

`data_idx`: 0\~1499 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 1500\~2999 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 3000\~4499 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 4500\~5999 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 6000\~7499 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 7500\~8999 -> 0th\~1499th data of `self.dbs[db_idx]`
`data_idx`: 9000\~9999 -> 0th\~999th data of `self.dbs[db_idx]`


`if data_idx >= len(self.dbs[db_idx]) * (self.max_db_data_num // len(self.dbs[db_idx]))`
This condition is making the sampling on the last batch be uniform.

**Comment by rainypurplesky** [comment]
Thank you for your clear explanation!!
But I wonder about the another implementation.
How about just performing `data_idx = random.randint(0,len(self.dbs[db_idx])-1)` in all case?
Would this cause any problems??

**Comment by hongsukchoi** [comment]
@rainypurplesky 

It seems to have no logical problem, but I don't recommend.
Normally, we want to make the model to see every data in datasets for one epoch.
Making sampled data to be independent from `index` can drop some data.

**Comment by rainypurplesky** [comment]
I appreciate your opinion! It helped me a lot :+1:
