### ISSUE TITLE
About environment

### ISSUE THREAD

**Issue by 109318401ntut** [hongsukchoi/Pose2Mesh_RELEASE#22]
Hello, thank you for your amazing implementation.
Is this Pose2Mesh_RELEASE repo were developed on windows 10 ?

**Comment by hongsukchoi** [comment]
Hi, it is developed on Ubuntu 18.04.
We used Python3.7, Pytorch >= 1.1.

**Comment by 109318401ntut** [comment]
Thanks for your reply.
