### ISSUE TITLE
Compatibility with Openpose 25 annotations?

### ISSUE THREAD

**Issue by qianlim** [hongsukchoi/Pose2Mesh_RELEASE#28]
Hi! I'd like to apply Pose2Mesh with my own data which has only OpenPose 25-joint annotations (which seems to be the 17 coco joints + neck + pelvis + 6 extra joints on the feet, as defined [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md#pose-output-format-body_25)). 
Now that Pose2Mesh uses your customized COCO joints (original 17 + neck + pelvis) for 3DPW training, can I directly apply that pretrained model to my task? 
If so, should I simply use the neck and pelvis joints that's contained in my openpose-25 annotations, or ignore them and recompute them using [this line of code](https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/32fb204c85a584b223158e732a205d08948cf093/data/PW3D/dataset.py#L138)?

Thanks in advance, I just wanna make sure I'm using your model in a strictly correct way (great work by the way!).

**Comment by hongsukchoi** [comment]
Sorry for the late reply, I was busy preparing CVPR...

I recommend the latter method (recomputing neck and pelvis), since the model is trained on such data.

Or you could retrain our model with the 25 joint annotations. If you want I can tell you the details.

And thanks for your compliment!

**Comment by qianlim** [comment]
Thank you! Let me try the recomputing and see if it produces satisfying results.

**Comment by zjuKirito** [comment]
> Thank you! Let me try the recomputing and see if it produces satisfying results.
@qianlim
Do you still remember the conclusion at that time? Can you share the details at that time? Thank you very much!
