### ISSUE TITLE
Broken link to models

### ISSUE THREAD

**Issue by mjpvz** [hongsukchoi/Pose2Mesh_RELEASE#33]
A link in the readme file is broken. 

> Download basicModel_f_lbs_10_207_0_v1.0.0.pkl, basicModel_m_lbs_10_207_0_v1.0.0.pkl, and  basicModel_neutral_lbs_10_207_0_v1.0.0.pkl from [here](https://smpl.is.tue.mpg.de/downloads) (female & male)..

The "here" link is broken and now only the neural model is available.

**Comment by hongsukchoi** [comment]
Hi, you should first register in this site: https://smpl.is.tue.mpg.de/
And download the pkl files
