### ISSUE TITLE
How to change mesh gender?

### ISSUE THREAD

**Issue by mjpvz** [hongsukchoi/Pose2Mesh_RELEASE#37]
I am running `demo/run.py ` with a human36 joint set. I am trying to create a mesh for a specific gender. 

In `SMPL.get_layer`, which is invoked when creating `mesh_model` in `demo/run.py` three different layers are created, one for each gender. However, then it appears that these gendered layers are the neutral layer is used for the face, or for the smpl joint regressor. How can I output a female/male mesh?

**Comment by hongsukchoi** [comment]
hmm, you have to re-train to output meshes of different genders.
Pose2Mesh is a model-free approach and you cannot change the gender parameter and get new gender mesh
