### ISSUE TITLE
MoVi dataset

### ISSUE THREAD

**Issue by ziqingcheryl** [hongsukchoi/Pose2Mesh_RELEASE#38]
In the original paper, it is mentioned that MoVi dataset is used to train PoseNet. However. no relevant parameters regarding training with MoVi dataset is found in sset/yaml/posenet_{input joint set}_train_{dataset list}.yml. I wonder how MoVi dataset comes into play here. Would you specify?

**Comment by hongsukchoi** [comment]
checkout AMASS database. it includes MoVi
