### ISSUE TITLE
The visualizations seem a bit odd

### ISSUE THREAD

**Issue by elk-april** [hongsukchoi/Pose2Mesh_RELEASE#4]
Hello，I run the demo/run.py, get these outputs:
![image](https://user-images.githubusercontent.com/22853879/102317234-29073980-3fb2-11eb-8f07-4c98e2bc7bcc.png)
![image](https://user-images.githubusercontent.com/22853879/102317351-5ce25f00-3fb2-11eb-96d2-913f5256dff6.png)

the right is the input and I use other pose estimation models to get 2D joints location.
the left is the output of pose2mesh.
the checkpoint is "pose2mesh_cocoJ_gt_train_human36_coco"
Would you like to tell me where the mistake is? 
Looking forward to your reply.

**Comment by hongsukchoi** [comment]
Hi @elk-april, thanks for your interest.

Could you provide the visualization of the input 2D joint locations? Inaccurate 2D joint locations may lead to inaccurate 3D mesh output. The input seem to be a truncated image, and this might have affected the 2D joint estimation.

**Comment by elk-april** [comment]
Thanks for replying.
Actually, the input of 2D joint estimation is a complete image.
![image](https://user-images.githubusercontent.com/22853879/102450418-4bac5780-4071-11eb-8fa9-226f1c675e90.png)

**Comment by hongsukchoi** [comment]
hmm... The 2D joint locations look okay. Did you add pelvis and neck joint locations?
Also the order of 2D joint input should follow  [this](https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/3504a149d88a01691f951bfd22aaff1476ee55f9/data/COCO/dataset.py#L54).
```
self.coco_joints_name = (
            'Nose', 'L_Eye', 'R_Eye', 'L_Ear', 'R_Ear', 'L_Shoulder', 'R_Shoulder', 'L_Elbow', 'R_Elbow', 'L_Wrist',
            'R_Wrist', 'L_Hip', 'R_Hip', 'L_Knee', 'R_Knee', 'L_Ankle', 'R_Ankle', 'Pelvis', 'Neck')
```

And could you show the visualization with the full 3D mesh output?

**Comment by elk-april** [comment]
Yeah, I use the center of R_Hip and L_Hip as the locations of Pelvis.
"full 3D mesh output" means all 3D mesh output of the video or complete image?
This is the visualization of one picture:
![image](https://user-images.githubusercontent.com/22853879/102451675-edcd3f00-4073-11eb-8968-4213c097de01.png)

**Comment by hongsukchoi** [comment]
Yes, I meant the complete image of the 3D mesh output. I guess you rotated the mesh, right?

I think the overall posture looks right but the limb details look inaccurate. 
This may be just from the depth ambiguity, but I think the visual results will be better if you use the pre-trained model from `pose2mesh_cocoJ_train_human36_coco_muco`.  `pose2mesh_cocoJ_gt_train_human36_coco` is trained with groundtruth input 2D joint locations and subtle errors from the input 2D joint locations in test time might cause larger errors on 3D mesh output.

So I recommend you to test the model with `pose2mesh_cocoJ_train_human36_coco_muco` and visualize the output.

**Comment by elk-april** [comment]
Yes, I rotate it.
Actually, I also use "pose2mesh_cocoJ_train_human36_coco_muco" to run the demo, the limb details look inaccurate too...
![image](https://user-images.githubusercontent.com/22853879/102454766-7a2e3080-4079-11eb-8f3c-5d46a1c8857c.png)
The upper extremities look better, but the lower extremities are still abnormally bent.

**Comment by hongsukchoi** [comment]
hmm.

I saw this kind of bent leg outputs when the input images were truncated, but your input look okay.
Could you email me the input image and input 2D joint locations to test myself?
my email: redarknight@snu.ac.kr

**Comment by elk-april** [comment]
No problem. Thank you very much!
