### ISSUE TITLE
test issue about PW3D

### ISSUE THREAD

**Issue by Hao-hui** [hongsukchoi/Pose2Mesh_RELEASE#40]
Hi,
I trained pose2mesh on Human36m using 
**"pose2mesh_human36J_train_human36.yml"**
, how can I test this model on PW3D ?
 I'm looking forward to hearing from you. Many thanks!

**Comment by hongsukchoi** [comment]
You can make your own test yaml file and write the saved checkpoint's directory like here
https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/e91bdd69077e964c5591f7c52b6f484d5180bd12/asset/yaml/pose2mesh_human36J_test_human36.yml#L37

**Comment by Hao-hui** [comment]
> 
Thank you for your prompt reply！
As you said, I modified it and  test_list as follows, but the problem doesn't seem to be solved.
![image](https://user-images.githubusercontent.com/82891524/160320310-232ed5b8-c62e-49df-8870-501b89efa4fc.png)
I have attached the screenshot of the problem, I guess it may be the problem of the number of joints, please help me how to modify it?  
![image](https://user-images.githubusercontent.com/82891524/160319695-8ac3fa26-b0e5-468a-a88d-39c2630b2e21.png)

**Comment by hongsukchoi** [comment]
aha.. now I understand the problem. Human36M and 3DPW have different joint sets. So basically you would not test the Human3.6M trained model on 3DPW. 

check this out: https://github.com/hongsukchoi/Pose2Mesh_RELEASE#running-pose2mesh

**Comment by Hao-hui** [comment]
I'm sorry for my negligence. Thank you very much for your patient answer. I will close this.
