### ISSUE TITLE
How may I get MANO parameters from pose2mesh model?

### ISSUE THREAD

**Issue by pzxszbry** [hongsukchoi/Pose2Mesh_RELEASE#46]
In the demo, it outputs the mesh and rendered joints on 2D image for MANO. Is there a method to output betas & poses instead of the mesh? I have the labeled hand joints, but need to extract mano parameters (betas, poses).

**Comment by hongsukchoi** [comment]
Pose2Mesh is a model-free method that directly regresses a 3D mesh without model parameters. 
You could re-train the Pose2Mesh attached with some layers that regress parameters. Refer to [this](https://github.com/mks0601/I2L-MeshNet_RELEASE)

Or you can use other projects like [this](https://github.com/namepllet/HandOccNet)

**Comment by pzxszbry** [comment]
Thanks for the quick reply, I will try the linked project.
