### ISSUE TITLE
visualization - 2D keypoints with input image

### ISSUE THREAD

**Issue by moonsh** [hongsukchoi/Pose2Mesh_RELEASE#63]
Thank you for sharing your work.

I just wanted to visualize the input image with 2d pose estimation using the 3DPW test data set to see if the 3d estimation is correct.

I found the below code for visualization but strangely the 2d pose and image are severely misaligned. This code is not available?
https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/master/data/PW3D/dataset.py#L216

**Comment by hongsukchoi** [comment]
Hi,

There are some things to check

1. Is the gt 2d pose aligned with the image?
2. Does the scale of `data['pred_pose2d']` match the image's width and height?

I think the visualization code in `get_item` should work ok, could you provide your visualization?

**Comment by moonsh** [comment]
This command I used for testing 
"python main/test.py --cfg asset/yaml/posenet_cocoJ_test_3dpw.yml"

One example looks like this. The 2D pose and image are not aligned. However, I checked the 3D pose looks fine.

![1](https://user-images.githubusercontent.com/13994270/235584802-93a0d654-71ba-43d9-8977-8964097c3615.png)



and also I found that the evaluation result is strange. It seems like something is wrong.

 MPJPE: 263.8583
Evaluation start...
COCO MPJPE (mm)    >> tot: 263.87
COCO PA-MPJPE (mm) >> tot: 114.80

**Comment by hongsukchoi** [comment]
Hmm, I recently changed the 3dpw annotation files and maybe that's the problem.

**Comment by moonsh** [comment]
I see. Can you share the previous one?

**Comment by moonsh** [comment]
I got the previous annotation file here. 
https://github.com/kasvii/GATOR/issues/2

**Comment by hongsukchoi** [comment]
@moonsh  Sorry for the late reply. I updated the annotation files and checked the visualization. And thank you for letting me know.
