### ISSUE TITLE
Draw overlay of human mesh and original picture

### ISSUE THREAD

**Issue by BennyWnj** [hongsukchoi/Pose2Mesh_RELEASE#7]
Hi, is there code to draw human mesh on top of the original rgb picture as displayed in the paper?

**Comment by hongsukchoi** [comment]
Hi, it’s in the demo code

**Comment by hongsukchoi** [comment]
Hi,
did you also comment this line?  
img = np.zeros((img_res, img_res, 3))  # dummy

**Comment by BennyWnj** [comment]
yes

**Comment by hongsukchoi** [comment]
Hi,
you should change this [line](https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/3504a149d88a01691f951bfd22aaff1476ee55f9/demo/run.py#L34), to`img_shape = 255 * renderer(pred_vertices, camera_translation, img / 255.)`

I have plan to update some codes, and I will update the demo code also.
Thank you for noting me!

**Comment by BennyWnj** [comment]
Thanks, that works.
